title: KetoDietFree
description: Honest keto diet guides, reviews, and tips.
url: "https://sumitimran.github.io"
baseurl: "/ketodite69.github.io"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

